[package]
name = "elements-frequency"
version = "0.1.0"
description = "Finds frequency of unique elements in a list chronologically."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
